model_name: autotoken
pretrained_args:
  pretrained_model_name_or_path: roberta-base
  num_labels: 2

results_dir: "/content/drive/My Drive/ToxicSpans/results/fixed/roberta_base_token"

args:
  output_dir: ${results_dir}/ckpts/
  evaluation_strategy: steps
  eval_steps: 500
  logging_steps: 500
  logging_first_step: true
  logging_dir: ${results_dir}/logs/
  learning_rate: 2e-5
  save_steps: 500
  per_device_train_batch_size: 4 # originally used 2
  per_device_eval_batch_size: 4 # originally used 2
  num_train_epochs: 3 #originally 5
  weight_decay: 0.01
  seed: 42

save_model_path: ${results_dir}/final_model/
