model_name: autotoken
name: roberta
n_steps: 50
type: token
sample_index: 100 # should be in [0,1999] for test
out_dir: "/content/drive/My Drive/ToxicSpans/results/IG/roberta_token"
word_out_file: ${out_dir}/${sample_index}/word_importances
token_out_file: ${out_dir}/${sample_index}/token_importances
viz_out_file: ${out_dir}/${sample_index}/viz.html
ground_truths_file: ./data/tsd_test_spans.csv
results_dir: "/content/drive/My Drive/ToxicSpans/results/roberta_token"
data_config:
  name: toxic_spans_tokens
  model_checkpoint_name: ${results_dir}/ckpts/checkpoint-2500
  train_files:
    validation: ./data/clean_trial.csv
  eval_files:
    test: ./data/tsd_test.csv
  label_cls: true
  cls_threshold: 0.3 # can be tuned
  token_threshold: 0.0 # can be tuned
  tokenizer_params:
    truncation: true
    max_length: 384 # originally we used 200
    padding: max_length
    return_offsets_mapping: true
    return_token_type_ids: true
pretrained_args:
  pretrained_model_name_or_path: ${data_config.model_checkpoint_name}
predictions_file: ${results_dir}/preds/spans-pred_original_test.txt
