train_file: ./data/tsd_train.csv
dev_file: ./data/tsd_trial.csv
test_files:
  - ./data/clean_train.csv
  - ./data/clean_trial.csv
  - ./data/tsd_test_spans.csv
  - ./data/tsd_train.csv
  - ./data/tsd_trial.csv
max_length: 192
save_dir: "/content/drive/My Drive/ToxicSpans/results/rnnsl_tsd_train/"
