model_name: autotoken
results_dir: "/content/drive/My Drive/ToxicSpans/results/fixed/spanbert_token"
dataset:
  name: toxic_spans_tokens
  model_checkpoint_name: ${results_dir}/ckpts/checkpoint-1500
  train_files:
    train: ./data/tsd_train.csv
    validation: ./data/tsd_trial.csv
    original_test: ./data/tsd_test_spans.csv
  eval_files:
    test: ./data/tsd_test.csv
  label_cls: true
  cls_threshold: 0.3 # can be tuned
  token_threshold: 0.0 # can be tuned
  tokenizer_params:
    truncation: true
    max_length: 384 # originally we used 200
    padding: max_length
    return_offsets_mapping: true
pretrained_args:
  pretrained_model_name_or_path: ${dataset.model_checkpoint_name}
with_ground: true
save_dir: ${results_dir}/preds/
