model_name: autospans
pretrained_args:
  pretrained_model_name_or_path: bert-base-uncased

results_dir: "/content/drive/My Drive/ToxicSpans/results/fixed/bert_base_spans"

args:
  output_dir: ${results_dir}/ckpts/
  evaluation_strategy: steps # originally epochs
  eval_steps: 500
  logging_steps: 500 # originally 200
  logging_dir: ${results_dir}/logs/
  learning_rate: 2e-5
  save_steps: 500
  per_device_train_batch_size: 4
  per_device_eval_batch_size: 4
  num_train_epochs: 3.0
  weight_decay: 0.01
  seed: 42

save_model_path: ${results_dir}/final_model/
